name: Build and Release Nexa UI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    outputs:
      artifact-name: ${{ steps.set-artifact.outputs.name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Install Rosetta
        if: matrix.os == 'macos-latest'
        run: |
          /usr/sbin/softwareupdate --install-rosetta --agree-to-license

      - name: Cache pip for Rosetta venv
        if: matrix.os == 'macos-latest'
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: macos-x86-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Build with PyInstaller
        run: |
          cd client
          pyinstaller UI.spec --noconfirm

      - name: Build universal macOS app
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          cd client

          # Build ARM64
          pyinstaller UI.spec --distpath dist_arm64

          # Set up Python x86_64 via Rosetta
          arch -x86_64 /usr/bin/python3 -m venv venv_x86
          . venv_x86/bin/activate
          arch -x86_64 pip install -r ../requirements.txt
          arch -x86_64 pip install pyinstaller
          arch -x86_64 pyinstaller UI.spec --distpath dist_x86_64

          # Combine both builds into a universal binary
          mkdir dist_universal
          cp -R dist_arm64/NexaChat.app dist_universal/
          lipo -create dist_arm64/NexaChat.app/Contents/MacOS/NexaChat dist_x86_64/NexaChat.app/Contents/MacOS/NexaChat -output dist_universal/NexaChat.app/Contents/MacOS/NexaChat

          # Archive the universal app
          cd dist_universal
          zip -r ../../nexachat-macos.zip NexaChat.app

      - name: Archive Windows EXE
        if: matrix.os == 'windows-latest'
        run: |
          $exe = Get-ChildItem -Path client/dist -Filter *.exe -Recurse | Select-Object -First 1
          Compress-Archive -Path $exe.FullName -DestinationPath nexachat-windows.zip
        shell: pwsh

      - name: Archive Linux Binary
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd client/dist
          tar -czvf ../../nexachat-linux.tar.gz NexaChat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nexachat-${{ matrix.os }}
          path: |
            nexachat-*.zip
            nexachat-*.tar.gz
          if-no-files-found: ignore

  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}