name: Node.js CI

on:
  push:
    branches: ["experimental"]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]  # Supprime 23.x car il semble instable
        # Voir le planning des versions Node.js : https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: bootstrap/package-lock.json  # Vérifie que ce fichier existe bien

    - name: Install dependencies
      working-directory: bootstrap
      run: npm ci

    - name: Build project
      working-directory: bootstrap
      run: npm run build --if-present

    - name: Run tests
      working-directory: bootstrap
      run: npm test
