name: Node.js CI

on:
  push:
    branches: ["dev", "experimental"]
  pull_request:
    branches: ["master", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: bootstrap/package-lock.json 

      - name: Install dependencies
        working-directory: bootstrap
        run: npm ci

      - name: Setup SQLite Database
        working-directory: bootstrap
        run: |
          sqlite3 db.sqlite "CREATE TABLE IF NOT EXISTS nodes (id INTEGER PRIMARY KEY AUTOINCREMENT, node TEXT UNIQUE);"
          sqlite3 db.sqlite "CREATE TABLE IF NOT EXISTS upnodes (id INTEGER PRIMARY KEY AUTOINCREMENT, node TEXT);"

      - name: Run tests
        working-directory: bootstrap
        run: npm test